name: Upload to PyPI
on: [push]

jobs:
  pypi-publish:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # OIDC for PyPI upload
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build packages
        run: |
          pip install flit
          flit build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
